"""empty message

Revision ID: 74deef40f439
Revises: 
Create Date: 2020-11-18 19:40:45.839409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74deef40f439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('connector',
    sa.Column('conn_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.plant_id'], ),
    sa.PrimaryKeyConstraint('conn_id')
    )
    op.create_table('sensor',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('telemetry_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.conn_id'], ),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('telemetry',
    sa.Column('tele_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.sensor_id'], ),
    sa.PrimaryKeyConstraint('tele_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_table('sensor')
    op.drop_table('connector')
    op.drop_table('plant')
    # ### end Alembic commands ###
